### ISSUE TITLE
Installing “fountain@0.8.3” failed.

### ISSUE THREAD

**Issue by Nyhde** [superlou/fountain-atom#109]
Hi,

I've been trying to install the fountain package for Atom for the past few days, and I'm starting to feel like I've exhausted pretty much all options I can think of. I'm running Atom x64 in portable mode on a Windows 10 laptop, but I've also tried everything on the version with an installer, and the same issue reoccurs.

Atom itself seems to be running fine, and installing other packages seems to be working, but of course it's the one package in which I'm actually interested that's causing me the most trouble.

When I start Atom and open up Setting/Install, search for Fountain, and try to install fountain 0.8.3, the Install bar seems to be loading for a while. And finally I simply get a red error message.

The error log file looks like this, and I'm having trouble deciphering it:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Ohjelmat\\Atom\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Ohjelmat\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Ohjelmat\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Ohjelmat\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/fountain/versions/0.8.3/tarball',
1 verbose cli   '--target=5.0.13',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose npm-session f89405faca4feb52
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/superlou/fountain-atom/legacy.tar.gz/v0.8.3 2795ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/fountain/versions/0.8.3/tarball fetched in 4416ms
9 timing stage:loadCurrentTree Completed in 4459ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule fountain@0.8.3 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/xregexp 547ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/sortablejs 577ms
19 silly pacote range manifest for xregexp@^3.1.1 fetched in 656ms
20 silly resolveWithNewModule xregexp@3.2.0 checking installable status
21 silly pacote range manifest for sortablejs@^1.6.1 fetched in 773ms
22 silly resolveWithNewModule sortablejs@1.10.2 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 947ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/underscore-plus 984ms (from cache)
25 silly pacote range manifest for underscore-plus@^1.0.0 fetched in 1020ms
26 silly resolveWithNewModule underscore-plus@1.7.0 checking installable status
27 silly pacote range manifest for atom-space-pen-views@^2.0.0 fetched in 1052ms
28 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 1113ms (from cache)
30 silly pacote range manifest for atom-package-deps@^4.6.0 fetched in 1212ms
31 silly resolveWithNewModule atom-package-deps@4.6.2 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/afterwriting 2445ms (from cache)
33 silly pacote range manifest for afterwriting@^1.11.0 fetched in 2573ms
34 silly resolveWithNewModule afterwriting@1.15.0 checking installable status
35 silly fetchPackageMetaData error for text@github:requirejs/text Error while executing:
35 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/requirejs/text.git
35 silly fetchPackageMetaData
35 silly fetchPackageMetaData
35 silly fetchPackageMetaData spawn git ENOENT
36 http fetch GET 304 https://registry.npmjs.org/lodash 1240ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/d3 1275ms (from cache)
38 silly pacote range manifest for lodash@^4.17.20 fetched in 1286ms
39 silly resolveWithNewModule lodash@4.17.20 checking installable status
40 silly pacote range manifest for d3@^3.4.1 fetched in 1378ms
41 silly resolveWithNewModule d3@3.5.17 checking installable status
42 http fetch GET 304 https://registry.npmjs.org/jquery 1415ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/stdio 1434ms (from cache)
44 silly pacote range manifest for jquery@^3.5.0 fetched in 1439ms
45 silly resolveWithNewModule jquery@3.5.1 checking installable status
46 silly pacote range manifest for stdio@^0.2.7 fetched in 1453ms
47 silly resolveWithNewModule stdio@0.2.7 checking installable status
48 http fetch GET 304 https://registry.npmjs.org/handlebars 1530ms (from cache)
49 silly pacote range manifest for handlebars@^4.6.0 fetched in 1567ms
50 silly resolveWithNewModule handlebars@4.7.6 checking installable status
51 http fetch GET 200 https://registry.npmjs.org/snyk 618ms
52 http fetch GET 200 https://registry.npmjs.org/snyk/-/snyk-1.398.1.tgz 222ms
53 silly pacote range manifest for snyk@^1.319.0 fetched in 964ms
54 silly resolveWithNewModule snyk@1.398.1 checking installable status
55 http fetch GET 304 https://registry.npmjs.org/aw-liner 1963ms (from cache)
56 silly pacote version manifest for aw-liner@0.0.2 fetched in 1991ms
57 silly resolveWithNewModule aw-liner@0.0.2 checking installable status
58 http fetch GET 304 https://registry.npmjs.org/aw-parser 2051ms (from cache)
59 http fetch GET 304 https://registry.npmjs.org/protoplast 2060ms (from cache)
60 silly pacote version manifest for aw-parser@0.1.1 fetched in 2073ms
61 silly resolveWithNewModule aw-parser@0.1.1 checking installable status
62 silly pacote version manifest for protoplast@2.0.3 fetched in 2098ms
63 silly resolveWithNewModule protoplast@2.0.3 checking installable status
64 timing stage:rollbackFailedOptional Completed in 1ms
65 timing stage:runTopLevelLifecycles Completed in 9277ms
66 silly saveTree apm-install-dir-2020817-14000-lzj1aa.5eug
66 silly saveTree `-- fountain@0.8.3
66 silly saveTree   +-- afterwriting@1.15.0
66 silly saveTree   | +-- aw-liner@0.0.2
66 silly saveTree   | +-- aw-parser@0.1.1
66 silly saveTree   | +-- d3@3.5.17
66 silly saveTree   | +-- handlebars@4.7.6
66 silly saveTree   | +-- jquery@3.5.1
66 silly saveTree   | +-- lodash@4.17.20
66 silly saveTree   | +-- protoplast@2.0.3
66 silly saveTree   | +-- snyk@1.398.1
66 silly saveTree   | `-- stdio@0.2.7
66 silly saveTree   +-- atom-package-deps@4.6.2
66 silly saveTree   +-- atom-space-pen-views@2.2.0
66 silly saveTree   +-- sortablejs@1.10.2
66 silly saveTree   +-- underscore-plus@1.7.0
66 silly saveTree   `-- xregexp@3.2.0
67 verbose stack Error: spawn git ENOENT
67 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
67 verbose stack     at onErrorNT (internal/child_process.js:415:16)
67 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
68 verbose cwd C:\Users\user\AppData\Local\Temp\apm-install-dir-2020817-14000-lzj1aa.5eug
69 verbose Windows_NT 10.0.18362
70 verbose argv "C:\\Ohjelmat\\Atom\\resources\\app\\apm\\bin\\node.exe" "C:\\Ohjelmat\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Ohjelmat\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Ohjelmat\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/fountain/versions/0.8.3/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
71 verbose node v10.20.1
72 verbose npm  v6.14.5
73 error code ENOENT
74 error syscall spawn git
75 error path git
76 error errno ENOENT
77 error enoent Error while executing:
77 error enoent undefined ls-remote -h -t ssh://git@github.com/requirejs/text.git
77 error enoent
77 error enoent
77 error enoent spawn git ENOENT
78 error enoent This is related to npm not being able to find a file.
79 verbose exit [ 1, true ]

My question is, what should I do to get fountain working? The idea of being able to write Fountain and being able to export PDFs from one application seems appealing to me.

Could anyone help me, please?

Thank you for your time.

**Comment by superlou** [comment]
This seems to be an issue with fetching package metadata for requirejs. It also might be related to #68. I was able to recreate this on Windows 10 with Fountain 0.8.3 and Atom 1.51.0 x64. Are you on a corporate or other filtered network? Any chance https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe might be related?

**Comment by superlou** [comment]
Something interesting, in `package-lock.js`, only one dependency is different than all the others:

https://github.com/superlou/fountain-atom/blob/e3157d3ffaf9d841fa291bf616d907e5713cdc60/package-lock.json#L343-L346

Most dependencies look like this:

https://github.com/superlou/fountain-atom/blob/e3157d3ffaf9d841fa291bf616d907e5713cdc60/package-lock.json#L362-L366

I wonder if git on Windows is failing to resolve the dependency in the same way as on Linux, or maybe on some networks?

**Comment by superlou** [comment]
It's not explicitly a Windows 10 (version 2004) thing, since it just worked on my personal laptop, though it did take a long time to resolve. I do have git for Windows installed on this machine.

The Github dependency for "text" is coming from afterwriting:

https://github.com/ifrost/afterwriting-labs/blob/9c30b196a889f340cbe5b74554fe45240aeea5b6/package.json#L65-L76

**Comment by Nyhde** [comment]
> Are you on a corporate or other filtered network?

I've now tried installing the Fountain package on several different networks, and the result is always the same.

**Comment by trochitv** [comment]
Same issue here. Would be interested in a solution as well.

**Comment by superlou** [comment]
> Same issue here. Would be interested in a solution as well.

@trochitv, are you on Windows?

**Comment by trochitv** [comment]
Wow that was quick.
Yes I am.

**Comment by trochitv** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\Jan\\AppData\\Local\\atom\\app-1.53.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Jan\\AppData\\Local\\atom\\app-1.53.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\Jan\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\Jan\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/fountain/versions/0.8.3/tarball',
1 verbose cli   '--target=6.1.12',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.4.0
4 verbose npm-session 6f832ac9697a99b0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/superlou/fountain-atom/legacy.tar.gz/v0.8.3 1059ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/fountain/versions/0.8.3/tarball fetched in 1120ms
9 timing stage:loadCurrentTree Completed in 1144ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule fountain@0.8.3 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 136ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/underscore-plus 136ms (from cache)
19 silly pacote range manifest for atom-package-deps@^4.6.0 fetched in 149ms
20 silly resolveWithNewModule atom-package-deps@4.6.2 checking installable status
21 silly pacote range manifest for underscore-plus@^1.0.0 fetched in 142ms
22 silly resolveWithNewModule underscore-plus@1.7.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/xregexp 143ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 147ms (from cache)
25 silly pacote range manifest for atom-space-pen-views@^2.0.0 fetched in 150ms
26 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
27 silly pacote range manifest for xregexp@^3.1.1 fetched in 149ms
28 silly resolveWithNewModule xregexp@3.2.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/sortablejs 150ms (from cache)
30 silly pacote range manifest for sortablejs@^1.6.1 fetched in 158ms
31 warn deprecated sortablejs@1.12.0: Object.assign was not transformed during the build of sortablejs, so it won't work in browsers where this does not exist (for example IE11). Please downgrade your version to 1.10.2 to keep supporting <=IE11 or upgrade to >2.0 where IE will no longer be supported.
32 silly resolveWithNewModule sortablejs@1.12.0 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/afterwriting 884ms (from cache)
34 silly pacote range manifest for afterwriting@^1.11.0 fetched in 902ms
35 silly resolveWithNewModule afterwriting@1.17.2 checking installable status
36 http fetch GET 304 https://registry.npmjs.org/pdfkit 93ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/lodash 95ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/d3 98ms (from cache)
39 silly pacote range manifest for pdfkit@^0.11.0 fetched in 102ms
40 silly resolveWithNewModule pdfkit@0.11.0 checking installable status
41 silly pacote range manifest for lodash@^4.17.20 fetched in 188ms
42 silly resolveWithNewModule lodash@4.17.20 checking installable status
43 silly pacote range manifest for d3@^3.4.1 fetched in 190ms
44 silly resolveWithNewModule d3@3.5.17 checking installable status
45 silly fetchPackageMetaData error for text@github:requirejs/text Error while executing:
45 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/requirejs/text.git
45 silly fetchPackageMetaData
45 silly fetchPackageMetaData
45 silly fetchPackageMetaData spawn git ENOENT
46 http fetch GET 304 https://registry.npmjs.org/jquery 220ms (from cache)
47 http fetch GET 304 https://registry.npmjs.org/handlebars 223ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/stdio 218ms (from cache)
49 silly pacote range manifest for handlebars@^4.6.0 fetched in 233ms
50 silly resolveWithNewModule handlebars@4.7.6 checking installable status
51 silly pacote range manifest for jquery@^3.5.0 fetched in 233ms
52 silly resolveWithNewModule jquery@3.5.1 checking installable status
53 silly pacote range manifest for stdio@^0.2.7 fetched in 230ms
54 silly resolveWithNewModule stdio@0.2.7 checking installable status
55 http fetch GET 304 https://registry.npmjs.org/snyk 244ms (from cache)
56 silly pacote range manifest for snyk@^1.319.0 fetched in 285ms
57 silly resolveWithNewModule snyk@1.427.0 checking installable status
58 http fetch GET 304 https://registry.npmjs.org/aw-liner 822ms (from cache)
59 silly pacote version manifest for aw-liner@0.0.2 fetched in 872ms
60 silly resolveWithNewModule aw-liner@0.0.2 checking installable status
61 http fetch GET 304 https://registry.npmjs.org/aw-parser 831ms (from cache)
62 silly pacote version manifest for aw-parser@0.1.1 fetched in 837ms
63 silly resolveWithNewModule aw-parser@0.1.1 checking installable status
64 http fetch GET 304 https://registry.npmjs.org/protoplast 834ms (from cache)
65 silly pacote version manifest for protoplast@2.0.3 fetched in 840ms
66 silly resolveWithNewModule protoplast@2.0.3 checking installable status
67 timing stage:rollbackFailedOptional Completed in 0ms
68 timing stage:runTopLevelLifecycles Completed in 2964ms
69 silly saveTree apm-install-dir-20201016-12208-kv5wjg.8ylbk
69 silly saveTree `-- fountain@0.8.3
69 silly saveTree   +-- afterwriting@1.17.2
69 silly saveTree   | +-- aw-liner@0.0.2
69 silly saveTree   | +-- aw-parser@0.1.1
69 silly saveTree   | +-- d3@3.5.17
69 silly saveTree   | +-- handlebars@4.7.6
69 silly saveTree   | +-- jquery@3.5.1
69 silly saveTree   | +-- lodash@4.17.20
69 silly saveTree   | +-- pdfkit@0.11.0
69 silly saveTree   | +-- protoplast@2.0.3
69 silly saveTree   | +-- snyk@1.427.0
69 silly saveTree   | `-- stdio@0.2.7
69 silly saveTree   +-- atom-package-deps@4.6.2
69 silly saveTree   +-- atom-space-pen-views@2.2.0
69 silly saveTree   +-- sortablejs@1.12.0
69 silly saveTree   +-- underscore-plus@1.7.0
69 silly saveTree   `-- xregexp@3.2.0
70 verbose stack Error: spawn git ENOENT
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
70 verbose stack     at onErrorNT (internal/child_process.js:456:16)
70 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
71 verbose cwd C:\Users\Jan\AppData\Local\Temp\apm-install-dir-20201016-12208-kv5wjg.8ylbk
72 verbose Windows_NT 10.0.19041
73 verbose argv "C:\\Users\\Jan\\AppData\\Local\\atom\\app-1.53.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Jan\\AppData\\Local\\atom\\app-1.53.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Jan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Jan\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/fountain/versions/0.8.3/tarball" "--target=6.1.12" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
74 verbose node v12.4.0
75 verbose npm  v6.14.8
76 error code ENOENT
77 error syscall spawn git
78 error path git
79 error errno ENOENT
80 error enoent Error while executing:
80 error enoent undefined ls-remote -h -t ssh://git@github.com/requirejs/text.git
80 error enoent
80 error enoent
80 error enoent spawn git ENOENT
81 error enoent This is related to npm not being able to find a file.
82 verbose exit [ 1, true ]

here is my log if it is any help.

**Comment by superlou** [comment]
Unfortunately, we've been unable to find a fix for this. The only thing in common seems to be that it happens on Windows and seems to be related to how the Afterwriting plugin pulls in the "text" package. I thought it was related to https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe, which mentions a possible work around, but I haven't been able to reliably recreate the issue to try it, since I'm usually on Linux.

**Comment by trochitv** [comment]
I see. Seems I have to move to Linux ^^

**Comment by trochitv** [comment]
Just recreated the issue on Ubuntu with a fresh install of atom.

**Comment by superlou** [comment]
I just checked again on Linux Mint 19.3. I was able to install both via the GUI and `apm`.

```
lsimons@bestever:~$ apm install fountain
Installing fountain to /home/lsimons/.atom/packages ✓
```

I'm still tentatively convinced it has something to do with resolving `ssh://git@github.com/requirejs/text.git` on some networks, but I don't know a better way to debug it. For a [sanity check](https://medium.com/anna-coding/solution-for-npm-err-enoent-undefined-ls-remote-h-t-18ab6f8274af), can you double check if `git` runs from your command line? Does the following clone the text repo?

```
git clone ssh://git@github.com/requirejs/text.git
```

**Comment by fhisch** [comment]
I was having an issue installing and found this thread. Per @superlou 's suggestion, I made sure a command-line accessible git was installed, which I got from here: https://git-scm.com/download/win

After installing it (and opening Atom fresh), I was able to install the fountain package. I hope this helps.

**Comment by superlou** [comment]
@trochitv Any chance that installing git as @fhisch did solves it? Unfortunately, I'm not sure a work around since it's because of [Afterwriting's dependencies](https://github.com/ifrost/afterwriting-labs/blob/master/package.json#L83). I created an [issue ticket](https://github.com/ifrost/afterwriting-labs/issues/136) with afterwriting, but I think we would first need requirejs/text to cut a release of the trunk to npm.

**Comment by trochitv** [comment]
Sorry for not getting back to you, and thank you for your time.

You are correct. I am not working with git (yet) and was not aware that a command-line accessible git was necessary for this package to function until your proposed sanity check. I then went ahead and installed git, but didn't get around to test again on  a rebooted machine until now. It is installed.

Thank you very much again!

**Comment by trochitv** [comment]
Sorry, to bother you again. I thought I could tackle this one myself, but aparently I can't, altough this is most likely a rookie mistake ... again:

The syntax highlighting works perfectly fine now, but neither the preview, nor the exported pdf seems to be created when the action is launched. It says so with a green checkmark, but the atom pdf viewer opens blanc and when I try to open the pdf with a different viewer it seems to not have been created at all. Neither the preview, nor the export pdf. 
Do I need to install something again to make the afterwriting part work?

**Comment by superlou** [comment]
@trochitv, since that seems like a new issue, could you create a new one for us to track it in? Please include an example of your script that demonstrates the bug, and a screenshot or two might help us.

**Comment by trochitv** [comment]
will do.

**Comment by trochitv** [comment]
I have done so.

**Comment by jrbostic** [comment]
@superlou Sorry, I haven't had a dev environment to work on this project for a while.  Just did a fresh install of Atom on my Windows laptop, and tried to install the atom fountain package.  It looks to me that sortable JS needs to drop or bump versions: 

"Object.assign was not transformed during the build of sortablejs, so it won't work in browsers where this does not exist (for example IE11). Please downgrade your version to 1.10.2 to keep supporting <=IE11 or upgrade to >2.0 where IE will no longer be supported."

**We're referencing a tag on sortablejs that doesn't exist.  Try targeting 1.10.2**

Full Stacktrace:

<embedded>:14 Installing package fountain failed Error: Installing “fountain@0.8.3” failed.
    at C:\Users\12532\AppData\Local\atom\app-1.53.0\resources\app\static\<embedded>:11:916775
    at r (C:\Users\12532\AppData\Local\atom\app-1.53.0\resources\app\static\<embedded>:11:911227)
    at s (C:\Users\12532\AppData\Local\atom\app-1.53.0\resources\app\static\<embedded>:14:1134640)
    at ChildProcess.<anonymous> (C:\Users\12532\AppData\Local\atom\app-1.53.0\resources\app\static\<embedded>:14:1134846)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) 
npm WARN deprecated sortablejs@1.12.0: Object.assign was not transformed during the build of sortablejs, so it won't work in browsers where this does not exist (for example IE11). Please downgrade your version to 1.10.2 to keep supporting <=IE11 or upgrade to >2.0 where IE will no longer be supported.
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/requirejs/text.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\12532\.atom\.apm\_logs\2020-12-19T15_48_48_945Z-debug.log

**Comment by jrbostic** [comment]
https://github.com/SortableJS/sortablejs/tree/1.10.2

**Comment by superlou** [comment]
@jrbostic, good point, and we should probably have an issue for that. I think the root issue is still that "requirejs/text" dependency from github.

**Comment by jrbostic** [comment]
@superlou Perhaps... but what strikes me as odd about that is that "undefined" in the stacktrace on that "npm ERR!" line... is that's where "git" would have been interpolated.  I mean... a project wont build with a non-existent dep version, right?  I'm wondering if we aren't being mislead/tricked by something here.  The solution can't be to install git.  Atom is broke, if that's the case.  Anyway... a non-existent dep is something in the way, in my mind.  Clear that out and we may be looking at a different error.  Idk

**Comment by jrbostic** [comment]
@superlou Oh, okay... I'm catching up.  That afterwriting dep.... that's where the problem is coming in.  Do you think some kind of local override could halt the attempt at resolving the dep there?  Like, what's done here:  https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

Also... may be able to figure why it was added like that in this PR: https://github.com/ifrost/afterwriting-labs/pull/133/files ... then potentially offer a solution.

Or downgrade Afterwriting to before these commits, for now?

**Comment by superlou** [comment]
I've been trying to get master up to the latest Afterwriting to solve #110. Turns out that the confirmation pop-up API has changed since we wrote it, and I can't figure out how to make your tests work with the new asynchronous API. That said, I don't think that will fix that dependency, and maybe something like overriding the nested NPM dependency might work? It feels a little gross.

**Comment by superlou** [comment]
With https://github.com/ifrost/afterwriting-labs/issues/136 resolved, we just need to wait for a new Afterwriting release and fix the test cases. The code itself in master should already be working.

**Comment by ifrost** [comment]
> With [ifrost/afterwriting-labs#136](https://github.com/ifrost/afterwriting-labs/issues/136) resolved, we just need to wait for a new Afterwriting release and fix the test cases. The code itself in master should already be working.

The change has been released in v1.17.3 and it's available in NPM.

**Comment by superlou** [comment]
@jrbostic Is there any chance you could take a look at those test cases on master? The ones related to the new message box API are failing, but if I try to use the old API, I had other problems.

**Comment by jrbostic** [comment]
@superlou Would be happy to!  But I'll need a window extending through this weekend.  Still not set up to work on the project and haven't seen the API changes yet.  These are dialogue windows that pop up during install and when rendering to pdf?

**Comment by superlou** [comment]
@jrbostic I think just the ones that happen when rendering to PDF, though I didn't know enough about them to look for others. Take as much time as you need. It looks like we managed to scratch the itch for a few people that needed it using the master, and this is a volunteer project. Have a happy holidays!
